a2/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('rst2html.urls')),
    url(r'^admin/', admin.site.urls),
]

rst2html/urls.py
from django.conf.urls import include, url
from . import views

app_name = 'rst2html'
urlpatterns = [
    url(r'^$', views.home_page, name='home_page'),
    url(r'^rst2html/$',views.rst2html, name = 'rst2html'),
    url(r'^upload/$',views.uploadrst, name = 'upload'),
    url(r'^uploadpage/$', views.uploadpage, name='uploadpage'),
    url(r'^uploadimage/$', views.uploadimage, name='uploadimage'),
    url(r'^imagecode/$', views.imagecode, name='imagecode'),
    url(r'^uploadimage/$', views.uploadimage, name='uploadimage'),
    url(r'^imagecode/$', views.imagecode, name='imagecode'),
    url(r'^login/compilers$', views.login_compilers, name='login_compilers'),
    url(r'^logout/compilers$', views.logout_compilers, name='logout_compilers'),
    url(r'^login.html$', views.login_page, name='login_page'),
    url(r'^register/compilers$', views.register_compilers, name='register_compilers'),
    url(r'^register.html$', views.register_page, name='register_page'),
    
]

rst2html/models.py
from django.db import models

rst2html/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.core.files.storage import default_storage
from django.contrib import auth
from django.contrib.auth.models import User
import os


def login_page(request):
    return render(request, 'rst2html/login.html')

def register_page(request):
    return render(request, 'rst2html/register.html')
def home_page(request):
    if request.user.username == "" :
        return render(request,'rst2html/login.html')
    else:
        return render(request,'rst2html/home_page.html')
def register_compilers(request):
    try:
        if request.POST['button'] == 'Submit':
            if request.method == 'POST':
                username = request.POST['username']
                password = request.POST['password']
                confirm_password = request.POST['confirm-password']
                e_mail = request.POST['e-mail']
                first_name = request.POST['first_name']
                last_name = request.POST['last_name']
                if username == '' or password == '' or confirm_password == '' or e_mail == '':
                    message = "Your data is not complete !!"
                    return render(request, 'rst2html/register.html', {'message': message})
                else:
                    if password == confirm_password:
                        user_list = User.objects.all()
                        for user in user_list:
                            if username == user.username:
                                message = 'Username is was already !!'
                                return render(request, "rst2html/register.html", {'message': message})
                        new_user = User.objects.create_user(username, e_mail, password)
                        new_user.is_staff = False
                        new_user.first_name = first_name
                        new_user.last_name = last_name
                        
                        new_user.save()
                    else:
                        message = "Passwords do not match !!"
                        return render(request, "rst2html/register.html", {'message': message})
            return redirect('/login.html')
        else:
            return redirect('/login.html')
    except:
        return redirect('/register.html')


def login_compilers(request):
    try:
        if request.POST['button'] == 'Login':
            if request.user.username != '':
                return HttpResponseRedirect('/')
            elif request.method == 'POST':
                username = request.POST['username']
                password = request.POST['password']
                user = auth.authenticate(username=username, password=password)
                if None != user:
                    auth.login(request, user)
                    return HttpResponseRedirect('/')
                else:
                    if username == '' and password == '':
                        return redirect('rst2html/login.html')
                    else:
                        message = 'Username not found !!'
                        return render(request, 'rst2html/login.html', {'message': message})
        else:
            return redirect('/register.html')
        return redirect('/')
    except:
        return redirect('/login.html')


def logout_compilers(request):
    if request.method == 'POST':
        auth.logout(request)
    return redirect('/login.html')


def rst2html(request):
    rst_name = request.GET['rstname']  
    textinput = open('rst2html/static/rst2html/{}.rst'.format(rst_name), 'w')
    textinput.write(request.GET['convert'])
    textinput.close()
    
    theme = request.GET['theme']  
    os.system('rst2html5 {} rst2html/static/rst2html/{}.rst > rst2html/templates/rst2html/{}.html'.format(theme,rst_name,rst_name))  
    htmlFile = open('rst2html/templates/rst2html/{}.html'.format(rst_name), 'r')
    html_content = ""
    for item in htmlFile:
        html_content = html_content + item  
    htmlFile.close()
    os.remove('rst2html/static/rst2html/{}.rst'.format(rst_name))  
    os.remove('rst2html/templates/rst2html/{}.html'.format(rst_name))  
    return HttpResponse(html_content)

def uploadrst(request):
    dirPath = 'rst2html/static/rst2html/'
    if request.FILES != {}:  
        rstFile = request.FILES['rstFile']
        saveFilePath = default_storage.save(dirPath,rstFile)
        os.rename(saveFilePath,'{}textinput.rst'.format(dirPath))
    if request.POST['theme']== "deck":   
        os.system('rst2html5 --deck-js --pretty-print-code --embed-content rst2html/static/rst2html/textinput.rst > rst2html/templates/rst2html/{}.html'.format(rstFile))
        return render(request,'rst2html/{}.html'.format(rstFile))
    elif request.POST['theme']== "clean":
        os.system('rst2html5 rst2html/static/rst2html/textinput.rst > rst2html/templates/rst2html/{}.html'.format(rstFile))    
        return render(request,'rst2html/{}.html'.format(rstFile))
    elif request.POST['theme']== "reveal":
        os.system('rst2html5 --jquery --reveal-js --pretty-print-code rst2html/static/rst2html/textinput.rst > rst2html/templates/rst2html/{}.html'.format(rstFile))    
        return render(request,'rst2html/{}.html'.format(rstFile))
    elif request.POST['theme']== "bootstrap":
        os.system('rst2html5 --bootstrap-css --pretty-print-code --jquery --embed-content rst2html/static/rst2html/textinput.rst > rst2html/templates/rst2html/{}.html'.format(rstFile))    
        return render(request,'rst2html/{}.html'.format(rstFile))
    return HttpResponseRedirect('/')

def uploadpage(request):
    request.session['imageName'] = ''  # clear image's name
    return render(request,'rst2html/uploadpage.html')

def uploadimage(request):
    file = request.FILES['pic']
    dirPath = 'rst2html/static/rst2html/images/'
    saveFilePath = default_storage.save(dirPath, file)
    os.rename(saveFilePath, '{}{}'.format(dirPath, file.name))
    request.session['imageName'] = file.name
    return HttpResponseRedirect(reverse('rst2html:imagecode'))

def imagecode(request):
    return render(request,'rst2html/imagecode.html')

rst2html/templates/rst2html/home_page.html
<!DOCTYPE html>
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'rst2html/style.css' %}" />
<html>
<head>

<title>RST2HTML</title>
<div id="header">
<h1>Welcome To RST2HTML<h1>
<form action="{% url 'rst2html:logout_compilers' %}" method="POST">
                        {% csrf_token %}
                        <button type="submit" ><b>Logout</b></button>
                    </form>
</div>
<script>
function validateForm() {
    var x = document.inputs["textinputform"]["convert"].value;
    if (x == null || x == "") {
        alert("you don't enter your text");
        return false;
    }
}

function textcolor(input) {
    var x = document.getElementById("textinput");
    if(input == 'red'){x.style.color = "red";}
    if(input == 'blue'){x.style.color = "blue";}
    if(input == 'black'){x.style.color = "black";}
    if(input == 'green'){x.style.color = "green";}
}


function font(input) {
  var x = document.getElementById("textinput");
  if(input == 'smallest'){x.style.fontSize = ".5em"; }
  if(input == 'smal'){x.style.fontSize = "1em"; }
  if(input == 'normal'){x.style.fontSize = "1.5em"; }
  if(input == 'large'){x.style.fontSize = "2em"; }
  if(input == 'largest'){x.style.fontSize = "2.5em"; }
}

function dropdownclose1() {
    document.getElementById("myDropdown1").classList.toggle("show");
}

function dropdownclose2() {
    document.getElementById("myDropdown2").classList.toggle("show");
}
function addText(event) {
			    var targ = event.target || event.srcElement;
			    document.getElementById("textinput").value += targ.textContent || targ.innerText;
			}
// Close the dropdown if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {

    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
}
function preview(){
    var choice = document.getElementById("choice");
    if(choice="clean"){    alert("555");}
}
function newPopup(url) {
	popupWindow = window.open(
		url,'popUpWindow','height=300,width=300,left=10,top=10,resizable=yes,scrollbars=yes,toolbar=yes,menubar=no,location=no,directories=no,status=yes')
}
</script>
</head>
<body>


<h3>UpLoad RST</h3><br>
<form action="{% url 'rst2html:upload' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="rstFile" id="rstFile" ><br>
         <select name="theme">
         <option value="clean">Clean</option>
         <option value="reveal">Reveal</option>
         <option value="deck">Deck</option>
         <option value="bootstrap">Bootstrap</option>
         <input type ="submit" value = "submit" />
         </select>
</form>

<br><br>
<p>Write Your Restructer Text Here!</p>
 <div class="dropdown">
    <button onclick="dropdownclose1()" class="dropbtn">Color</button>
    <div id="myDropdown1" class="dropdown-content">
      <a  href="javascript:void(0);"onclick="textcolor('red')" >red</a>
      <a  href="javascript:void(0);"onclick="textcolor('blue')">blue</a>
      <a  href="javascript:void(0);"onclick="textcolor('black')">black</a>
      <a  href="javascript:void(0);"onclick="textcolor('green')">green</a>
    </div>
  </div>


 <div class="dropdown">
    <button  onclick="dropdownclose2()" class="dropbtn">Size</button>
    <div id="myDropdown2" class="dropdown-content">
     <a href="javascript:void(0);" onclick="font('smallest')">
<span >Smallest</span></a>
      <a  href="javascript:void(0);" onclick="font('small')">
<span >Small</span></a>
      <a href="javascript:void(0);" onclick="font('normal')">
<span >Normal</span></a>
      <a href="javascript:void(0);" onclick="font('large')">
<span >Large</span></a>
      <a href="javascript:void(0);" onclick="font('largest')">
<span >Largest</span></a>
    </div>
  </div>
Images :
        <a href="JavaScript:newPopup({% url 'rst2html:uploadpage' %});" >Upload</a>
<div id =section>
<form name = "textinputform" action ="{% url 'rst2html:rst2html' %}"  onsubmit="return validateForm()">
<b> Name :</b>
<input type="text" name="rstname" placeholder="Enter your Presentation name here" maxlength="200" size="40">
<center><textarea name="convert" id="textinput"  rows="20" cols="100"  style="width: 1000px; height: 500px;" class="textbox"  placeholder="Enter Your Restructuretext..." ></textarea></center>
  </center>
  <center>
  <select name="theme" id="theme" >
            <option value="--deck-js --pretty-print-code --embed-content" >deck</option>
            <option value="">clean</option>
            <option value="--jquery --reveal-js --pretty-print-code">reveal</option>
            <option value="--bootstrap-css --pretty-print-code --jquery --embed-content">bootstrap</option>
  </select>
  <input type ="submit"  value = "submit"   />
 </form>
<div ng-app="previewSlides" ng-controller="previewSlidesController">
            <button ng-click="showPreview()" formaction="{% url 'rst2html:rst2html' %}"
                    formtarget="preview">
                Preview
            </button>
        
            <button ng-show="displayStatus" formaction="{% url 'rst2html:rst2html' %}"
                    formtarget="preview">
                Refresh
            </button>
            <br><br>
            <iframe ng-show="displayStatus" name="preview" width="100%" height="500"></iframe>
        </div>
</div>


</body>
</html>